FROM microsoft/dotnet:2.0-sdk AS build
WORKDIR /src

# copy csproj and restore as distinct layers
COPY ./src/*.sln .
COPY ./src/api/*.csproj ./api/
COPY ./src/api.tests/*.csproj ./api.tests/
RUN dotnet restore

# copy and build everything else
COPY ./src/api/. ./api/
COPY ./src/api.tests/. ./api.tests/

RUN dotnet build

FROM build AS testrunner
WORKDIR /src/api.tests
# ENTRYPOINT ["dotnet", "test","--logger:trx"]
ENTRYPOINT ["/bin/bash", "-c", "sleep infinity"]