version: '3'
services:
  webapi:
    build: .
    # image: dnc/web_api_sample
    container_name: web_api_sample
    ports:
    - "5001:5001"
    environment:
    - ASPNETCORE_URLS=http://+:5001
  test_runner:
    build: 
      context: .
      dockerfile: Dockerfile.test
    container_name: test_runner